---
title: "Présentation du cours"
---

# Présentation du cours

# Séance 1 Introduction

# Séance 2 : Le Travail Aujourd’hui

• Juan Sébastian Carbonell, postdoctorant au Groupe d’études et de
recherche permanent sur l’industrie et les salariés de l’automobile
(Gerpisa), à l’École normale supérieure (ENS) Paris-Saclay • “Travailler
dans l’industrie automobile aujourd’hui. Entre délocalisations,
intensification et digitalisation” (publié dans “Que sait‐on du travail
?” \#

# Séance 3 : Genre & Élite

• Sophie Louey, post-doctorante au CEET • “Je suis une femme, je suis un
patron” : les femmes dirigeantes dans les groupements patronaux” in
Genre, images et représentations dans les sphères de l’éducation, de la
formation et du travail, Presses universitaires de Rouen et du Havre,
2019

# Séance 4 : Mixité

• Pierre Bataille, maitre de conférence, Université de Grenoble • «Les
paradoxes de la mixité. Les conséquences de l’introduction de la mixité
aux con- cours d’entrée des Écoles normales supérieures de Saint-Cloud,
Fontenay-aux-Roses et Lyon»,Sociétés contemporaines, 2011/3

# Séance 5 : Genre et Petite Enfance

• Geneviève Cresson, professeur émerité de sociologie, Université
Lille 1. • “Indicible mais omniprésent : le genre dans les lieux
d’accueil de la petite enfance” (Cahiers du Genre, 2010/2, n° 49, pages
15-33).

# Séance 6 : Migrations

• Abdoul-Malik Ahmad, Chercheur postdoctoral/Université Laval (Québec),
• “Négocier l’articulation des temps sociaux entre travail salarié,
commerce et famille : le cas des femmes migrantes originaires des
Comores” (Temporalités, n° 33, 2021/1, “Temps et migrations”).

# Séance 7 : Violences au travail

• DERUELLE Farah, doctorante en sociologie, CERTOP, Toulouse 2 • «La
sexualité en colloque, une «parenthèse enchantée»? Violences et rituels
profession- nels à l’épreuve de l’égalité des carrières scientifique »,
Terrains & travaux, 2022/1 (N° 40), p. 89-111.
